# Generated by Django 5.1.6 on 2025-02-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
